-- Insert Organizations
INSERT INTO organizations (name, description, logo_url, website_url, email, phone, address, city, state, country, specializations, rating) VALUES
('Mindful Care Clinic', 'A comprehensive mental health clinic offering therapy, counseling, and psychiatric services.', NULL, 'https://mindfulcare.com', 'info@mindfulcare.com', '+1-555-0101', '123 Wellness St', 'Portland', 'OR', 'USA', '{"Depression", "Anxiety", "Trauma"}', 4.8),
('Urban Mental Health', 'Progressive mental health center with focus on modern therapy techniques and community wellness.', NULL, 'https://urbanmh.com', 'contact@urbanmh.com', '+1-555-0102', '456 Healing Ave', 'Seattle', 'WA', 'USA', '{"Anxiety", "Bipolar Disorder", "OCD"}', 4.6),
('Serenity Wellness Center', 'Holistic approach to mental health combining therapy with wellness activities.', NULL, 'https://serenity-wellness.com', 'hello@serenity.com', '+1-555-0103', '789 Peace Rd', 'San Francisco', 'CA', 'USA', '{"Stress", "Work-life Balance", "Mindfulness"}', 4.9),
('Hope & Healing', 'Specialized center for trauma recovery and grief counseling with compassionate professionals.', NULL, 'https://hopeandheal.com', 'support@hopeandheal.com', '+1-555-0104', '321 Recovery Ln', 'Austin', 'TX', 'USA', '{"Trauma", "Grief", "PTSD"}', 4.7),
('Bright Futures Psychology', 'Young adult mental health specialists with experience in life transitions and identity issues.', NULL, 'https://brightfutures.com', 'info@brightfutures.com', '+1-555-0105', '654 Future Way', 'Denver', 'CO', 'USA', '{"Life Transitions", "Identity", "College Stress"}', 4.5);

-- Insert Therapists
INSERT INTO therapists (organization_id, name, bio, photo_url, specializations, languages, license_number, rating, available) VALUES
((SELECT id FROM organizations WHERE name = 'Mindful Care Clinic'), 'Dr. Sarah Mitchell', 'Licensed Clinical Psychologist with 12 years of experience in cognitive-behavioral therapy.', NULL, '{"CBT", "Depression", "Anxiety"}', '{"English"}', 'CA-PSY-12345', 4.9, true),
((SELECT id FROM organizations WHERE name = 'Mindful Care Clinic'), 'James Chen', 'Licensed Marriage and Family Therapist specializing in relationship dynamics.', NULL, '{"Couples", "Family", "Communication"}', '{"English", "Mandarin"}', 'CA-LMFT-12346', 4.7, true),
((SELECT id FROM organizations WHERE name = 'Urban Mental Health'), 'Dr. Lisa Rodriguez', 'Board-certified psychiatrist with expertise in medication management and mood disorders.', NULL, '{"Bipolar Disorder", "Depression", "Medication"}', '{"English", "Spanish"}', 'WA-PSY-12347', 4.8, true),
((SELECT id FROM organizations WHERE name = 'Urban Mental Health'), 'Michael Thompson', 'Licensed Counselor specializing in anxiety disorders and exposure therapy.', NULL, '{"Anxiety", "OCD", "Panic"}', '{"English"}', 'WA-LPC-12348', 4.6, false),
((SELECT id FROM organizations WHERE name = 'Serenity Wellness Center'), 'Dr. Emily Watson', 'Clinical psychologist focused on mindfulness-based interventions and chronic pain.', NULL, '{"Mindfulness", "Stress", "Chronic Pain"}', '{"English"}', 'CA-PSY-12349', 4.9, true),
((SELECT id FROM organizations WHERE name = 'Serenity Wellness Center'), 'Aisha Williams', 'Licensed Professional Counselor with background in wellness coaching and lifestyle change.', NULL, '{"Wellness", "Life Balance", "Motivation"}', '{"English"}', 'CA-LPC-12350', 4.7, true),
((SELECT id FROM organizations WHERE name = 'Hope & Healing'), 'Dr. David Martinez', 'Trauma-specialized therapist with EMDR and somatic experiencing certification.', NULL, '{"Trauma", "PTSD", "EMDR"}', '{"English", "Spanish"}', 'TX-PSY-12351', 4.8, true),
((SELECT id FROM organizations WHERE name = 'Hope & Healing'), 'Jennifer Lee', 'Grief counselor and bereavement specialist with compassionate approach.', NULL, '{"Grief", "Bereavement", "Loss"}', '{"English"}', 'TX-LPC-12352', 4.8, true),
((SELECT id FROM organizations WHERE name = 'Bright Futures Psychology'), 'Dr. Robert Chang', 'Psychologist specializing in young adult development and life transitions.', NULL, '{"Young Adult", "Life Transitions", "Development"}', '{"English", "Cantonese"}', 'CO-PSY-12353', 4.6, true),
((SELECT id FROM organizations WHERE name = 'Bright Futures Psychology'), 'Amanda Foster', 'Licensed counselor specializing in college transition and academic stress.', NULL, '{"College", "Academic", "Transition"}', '{"English"}', 'CO-LPC-12354', 4.7, true);
